### ISSUE TITLE
Add ServiceManager 4 support

### ISSUE THREAD

**Issue by arhimede** [dotkernel/api#265]

**Comment by alexmerlin** [comment]
This will have to wait until some dependencies add support for `laminas/laminas-service-amanager:4.x`.

Tried to install it in DotKernel API using:

```shell
composer require laminas/laminas-servicemanager:^4.0
```

Below is the output:

```text
./composer.json has been updated
Running composer update laminas/laminas-servicemanager
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laminas/laminas-servicemanager ^4.0, found laminas/laminas-servicemanager[4.0.0, 4.0.1, 4.0.2, 4.1.0] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - dotkernel/dot-cli is locked to version 3.6.0 and an update of this package was not requested.
    - dotkernel/dot-cli 3.6.0 requires laminas/laminas-servicemanager ^3.11.1 -> found laminas/laminas-servicemanager[3.11.1, ..., 3.22.1] but it conflicts with your root composer.json require (^4.0).
  Problem 3
    - dotkernel/dot-mail is locked to version 4.2.0 and an update of this package was not requested.
    - dotkernel/dot-mail 4.2.0 requires laminas/laminas-servicemanager ^3.22 -> found laminas/laminas-servicemanager[3.22.0, 3.22.1] but it conflicts with your root composer.json require (^4.0).
  Problem 4
    - laminas/laminas-inputfilter is locked to version 2.30.1 and an update of this package was not requested.
    - laminas/laminas-inputfilter 2.30.1 requires laminas/laminas-servicemanager ^3.21.0 -> found laminas/laminas-servicemanager[3.21.0, 3.22.0, 3.22.1] but it conflicts with your root composer.json require (^4.0).
  Problem 5
    - laminas/laminas-text is locked to version 2.11.0 and an update of this package was not requested.
    - laminas/laminas-text 2.11.0 requires laminas/laminas-servicemanager ^3.22.0 -> found laminas/laminas-servicemanager[3.22.0, 3.22.1] but it conflicts with your root composer.json require (^4.0).
  Problem 6
    - dotkernel/dot-log 3.5.1 requires laminas/laminas-servicemanager ^3.22 -> found laminas/laminas-servicemanager[3.22.0, 3.22.1] but it conflicts with your root composer.json require (^4.0).
    - dotkernel/dot-errorhandler 3.4.1 requires dotkernel/dot-log ^3.4 -> satisfiable by dotkernel/dot-log[3.5.1].
    - dotkernel/dot-errorhandler is locked to version 3.4.1 and an update of this package was not requested.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

---

## Conclusion

In order to use `laminas/laminas-service-amanager:4.x` in DotKernel API,

- we need to add support for it in the following packages:

  - [ ] dotkernel/dot-cli - https://github.com/dotkernel/dot-cli/issues/37
  - [ ] dotkernel/dot-log - https://github.com/dotkernel/dot-log/issues/44
  - [ ] dotkernel/dot-mail - https://github.com/dotkernel/dot-mail/issues/56

- Laminas needs to add support for it in the following packages:

  - [ ] laminas/laminas-inputfilter
  - [ ] laminas/laminas-text

**Comment by arhimede** [comment]
We should focus on this one 
https://github.com/laminas/laminas-servicemanager
and all of other blocking components

**Comment by arhimede** [comment]
https://github.com/laminas/laminas-servicemanager/releases/tag/4.0.0

**Comment by arhimede** [comment]
See this issue, related

https://github.com/laminas/laminas-servicemanager/issues/216

**Comment by arhimede** [comment]
@alexmerlin check if this can be closed , and if we can use SM4

**Comment by alexmerlin** [comment]
Cannot be closed yet.
Reason in my https://github.com/dotkernel/api/issues/327#issuecomment-2912063079 .
